#!{{pkgPathFor "core/bash"}}/bin/bash

exec 2>&1

# Call the script to block until user accepts the MLSA via the package's config
{{pkgPathFor "chef/mlsa"}}/bin/accept {{cfg.mlsa.accept}}

export DBNAME="{{cfg.storage.database}}"
export DBUSER="{{cfg.storage.user}}"

echo "------------  clocal-user-service - ensure-service-database => $DBNAME ------------"
pg-helper ensure-service-database "$DBNAME"
echo "------------  dlocal-user-service - create-extension => $DBNAME ------------"
pg-helper create-extension "$DBNAME" pgcrypto
echo "------------  dlocal-user-service - fix-permissions => $DBNAME ------------"
pg-helper fix-permissions "$DBNAME"

echo "------------   users serve yo =>  ------------"
exec users serve {{pkg.svc_config_path}}/config.yml